In [5]:
import pandas as pd

In [6]:
# import results.csv
results = pd.read_csv("results.csv", sep = ',')
# convert to set to avoid multiple entries and back to list for iterable
mov_li = list(set(results["movie_or_TV_name"].tolist()))
# record the number of shared actors by list comprehension
num_actors = [(results.movie_or_TV_name == movie).sum() for movie in mov_li]

In [11]:
# Create and sort data frame for recommendations
rec = pd.DataFrame(data={"movie or TV show":mov_li, "number of shared actors":num_actors})
rec = rec.sort_values(by="number of shared actors", ascending=False )
# Tidying up the Table
rec = rec.reset_index()
rec = rec.drop("index", axis =1)
# Show the top 20 reccomedations
rec.head(20)

                  movie or TV show  number of shared actors
0                          Friends                      823
1                               ER                      182
2            Entertainment Tonight                      136
3   CSI: Crime Scene Investigation                      135
4                         Seinfeld                      122
5                            Today                      116
6                             NCIS                      114
7   The Tonight Show with Jay Leno                      110
8                        NYPD Blue                      105
9               Jimmy Kimmel Live!                      103
10                  Criminal Minds                       95
11                  Grey's Anatomy                       93
12                Diagnosis Murder                       92
13   Late Night with Conan O'Brien                       92
14               Days of Our Lives                       90
15                   The West Wing                       87
16                  Celebrity Page                       86
17             The Drew Carey Show                       85
18                         Charmed                       84
19                 Without a Trace                       83